enum colour {black,blue,cyan,darkgray,gray,green,lightgray,magenta,orange,pink,red,white,yellow};
typedef enum colour colour;

void stepOn();
void stepOff();
void setBackgroundSize(int x, int y);
void drawLine(int,int,int,int);
void drawRect(int,int,int,int);
void drawOval(int,int,int,int);
void drawArc(int,int,int,int,int,int);
void fillRect(int,int,int,int);
void fillOval(int,int,int,int);
void drawString(char*,int,int);
void postString(char*);
void postClear();
void drawImage(char*,int,int,int,int);
char* translateColour(colour);
void setColour(colour);
void addStroke(colour);
void setGradient(colour,colour,int,int);
void setRadialGradient(colour,colour);
void turtleMode(int,int);
void turtleModeOff();
void forward(int);
void turn(int);
void setPosition(int,int);
void setAngle(int);
void setBackgroundColour(colour);
void clear(colour);