enum colour {black,blue,cyan,darkgray,gray,green,lightgray,magenta,orange,pink,red,white,yellow};
typedef enum colour colour;

void stepOn();
void stepOff();
void setBackgroundSize(double x, double y);
void drawLine(double,double,double,double);
void drawRect(double,double,double,double);
void drawOval(double,double,double,double);
void drawArc(double,double,double,double,double,double);
void drawQuadCurve(double,double,double,double,double,double);
void fillRect(double,double,double,double);
void fillOval(double,double,double,double);
void drawString(char*,double,double);
void postString(char*);
void postClear();
void drawImage(char*,double,double,double,double);
char* translateColour(colour);
void setColour(colour);
void setLineWidth(double);
void setGradient(colour,colour,double,double);
void setRadialGradient(colour,colour);
void turtleMode(double,double);
void turtleModeOff();
void forward(double);
void turn(double);
void setPosition(double,double);
void setAngle(double);
void setBackgroundColour(colour);
void clear(colour);